---
- name: AWS Cloudtrail | Copy key file to server
  copy:
    src: "{{ aws_credentials_file }}"
    dest: "/tmp/aws_credentials_file.yaml"

- name: AWS Cloudtrail | Make key file folder
  file:
    path: /etc/logstash/keys
    state: directory

- name: AWS Cloudtrail | Remove old key file
  file:
    path: /etc/logstash/keys/aws_credentials_file.yaml
    state: absent

- name: AWS Cloudtrail | Copy key file to key file folder
  command: mv /tmp/aws_credentials_file.yaml /etc/logstash/keys/
