---
- name: Google Pubsub | Copy JSON key file to server
  copy:
    src: "{{ gcp_json_key_file }}"
    dest: "/tmp/gcp_json_key_file.json"

- name: Google Pubsub | Make key file folder
  file:
    path: /etc/logstash/keys
    state: directory

- name: Google Pubsub | Remove old key file
  file:
    path: /etc/logstash/keys/gcp_json_key_file.json
    state: absent

- name: Google Pubsub | Copy key file to key file folder
  command: mv /tmp/gcp_json_key_file.json /etc/logstash/keys/
