---
- name: Copy Pub/Sub input plugin file to server
  copy:
     src: logstash-offline-plugin-pubsub-input-6.6.0.zip
     dest: /tmp/logstash-offline-plugin-pubsub-input-6.6.0.zip
  when: agentType=="googlePubSub"
- name: Install google_pubsub input plugin
  command: >	  command: >
    ./bin/logstash-plugin install file:////tmp/logstash-offline-plugin-pubsub-input-6.6.0.zip
    chdir={{ logstash_dir }}
