---
- name: Get list of installed plugins.
  command: >
    ./bin/logstash-plugin list
    chdir={{ logstash_dir }}
  register: logstash_plugins_list
  changed_when: false

- name: Copy json_encode plugin file to server
  copy:
     src: logstash-offline-plugin-json-encode-6.6.0.zip
     dest: /tmp/logstash-offline-plugin-json-encode-6.6.0.zip

- name: Install json_encode plugin
  command: >
    ./bin/logstash-plugin install file:////tmp/logstash-offline-plugin-json-encode-6.6.0.zip
    chdir={{ logstash_dir }}

- include: plugins-aws-cloudtrail.yml
  when: agentType=="awsCloudtrail"

- include: plugins-google-pubsub.yml
  when: agentType=="googlePubSub"

- name: Install configured plugins.
  command: >
    ./bin/logstash-plugin install {{ item }}
    chdir={{ logstash_dir }}
  with_items: "{{ logstash_install_plugins }}"
  when: "item not in logstash_plugins_list.stdout"
  notify: restart logstash

- name: Change directory ownership & permissions
  file:
    path: /var/lib/logstash
    recurse: yes
    owner: logstash
    mode: 0755

