---
- name : Check Mandatory Variables For Install
  debug:
    msg:
      - ProjectName:{{ projectName | mandatory }}
      - UserName:{{ userName | mandatory }}
      - Sampling Interval:{{ samplingInterval | mandatory }}
      - Agent Type:{{ agentType | mandatory }}
      - License Key:{{ licenseKey | mandatory }}
      - Update APT:{{ apt_update | mandatory }}
- name: SELinux | Check for SELinux
  become: yes
  stat:
    path: /etc/selinux/config
  register: p
- name: SELinux | Disable SELinux
  become: yes
  selinux:
    state: disabled
  when: p.stat.exists == True
- name: Delete Old zip Bundle for Agent
  become: yes
  file:
    state: absent
    path: "{{ansible_env.HOME}}/insightagent.zip"
- name: Delete Old Agent Code
  become: yes
  file:
    state: absent
    path: "{{ansible_env.HOME}}/InsightAgent-master"
- name: Delete ifagent Cron Configuration
  become: yes
  file:
    state: absent
    path: /etc/cron.d/ifagent
- name: Copy Agent Code on Machines
  become: yes
  copy:
    src: ../files/insightagent.zip
    dest: "{{ansible_env.HOME}}"
    mode: 0644
- name: Untar the Agent Code
  shell: '/usr/sbin/unzip -o {{ansible_env.HOME}}/insightagent.zip -d {{ansible_env.HOME}}'
- name: Installer permission
  file:
    path: '{{ansible_env.HOME}}/InsightAgent-master/hypervisor/install.sh'
    mode: 0777
- name: Deploy hypervisor Agent
  shell: "unset http_proxy https_proxy && ./hypervisor/install.sh
    -i {{ projectName }}
    -u {{ userName }}
    -k {{ licenseKey }}
    -s {{ samplingInterval }}
    -r {{ samplingInterval }}
    -t {{ agentType }}
    -w {{ reportingUrl }}"
  become: true
  args:
    chdir: "{{ansible_env.HOME}}/InsightAgent-master/"
- name: Delete zip Bundle for Agent
  file:
    state: absent
    path: "{{ansible_env.HOME}}/insightagent.zip"