---
- name: Check for existing project
  become: yes
  stat:
    path: "{{ansible_env.HOME}}/InsightAgent-master"
  register: project_dir
  when: projectDir is not defined
- name: Check for existing project
  become: yes
  stat:
    path: "{{ projectDir }}"
  register: project_dir
  when: projectDir is defined
- name: Install Syscall Agent
  command: syscall/installLttng.py -d {{homeDir}}
  become: true
  become_flags: '-E'
  args:
    chdir: "{{ansible_env.HOME}}/InsightAgent-master/"
  when: project_dir.stat.exists and projectDir is not defined
- name: Install Syscall Agent
  command: syscall/installLttng.py -d {{homeDir}}
  become: true
  become_flags: '-E'
  args:
    chdir: "{{ projectDir }}"
  when: project_dir.stat.exists and projectDir is defined
- name: Deploy Syscall Agent
  command: ./getSysTrace.sh -t {{tracingInterval}}
  become: true
  become_flags: '-E'
  args:
    chdir: "{{ projectDir }}/syscall"
  when: project_dir.stat.exists and projectDir is defined
- name: Deploy Syscall Agent
  command: ./getSysTrace.sh -t {{tracingInterval}}
  become: true
  become_flags: '-E'
  args:
    chdir: "{{ansible_env.HOME}}/InsightAgent-master/syscall"
  when: project_dir.stat.exists and projectDir is not defined
