---
- name : Check Mandatory Variables For Install
  debug:
    msg:
      - tracingInterval:{{ tracingInterval | mandatory }}
- name: Check for existing project
  stat:
    path: "{{ projectDir }}"
  register: project_dir
  when: projectDir != ""
- name: Check for existing project
  stat:
    path: "{{ansible_env.HOME}}/InsightAgent-master"
  register: default_dir
  when: projectDir == ""
- name: Install Syscall Agent
  shell: "http_proxy={{ http_proxy }} syscall/installLttng.py -d {{ansible_env.HOME}}/InsightAgent-master/"
  become: true
  args:
    chdir: "{{ansible_env.HOME}}/InsightAgent-master/"
  when: projectDir == "" and default_dir.stat.exists
- name: Install Syscall Agent
  shell: "http_proxy={{ http_proxy }} syscall/installLttng.py -d {{projectDir}}"
  become: true
  args:
    chdir: "{{ projectDir }}"
  when: projectDir != ""  and project_dir.stat.exists
- name: Deploy Syscall Agent
  command: ./getSysTrace.sh -t {{tracingInterval}}
  become: true
  become_flags: '-E'
  args:
    chdir: "{{ projectDir }}/syscall"
  when: projectDir != "" and project_dir.stat.exists
- name: Deploy Syscall Agent
  command: ./getSysTrace.sh -t {{tracingInterval}}
  become: true
  become_flags: '-E'
  args:
    chdir: "{{ansible_env.HOME}}/InsightAgent-master/syscall"
  when: projectDir == "" and default_dir.stat.exists
- name: Start Syscall Agent Listener
  shell: "(no_proxy= {{ no_proxy }} ./reporting_send.py -d {{projectDir}}/syscall -D {{projectDir}} &)"
  become: true
  async: 10
  poll: 0
  become_flags: '-E'
  args:
    chdir: "{{ projectDir }}/syscall"
  when: projectDir != ""  and project_dir.stat.exists
- name: Start Syscall Agent Listener
  shell: "(no_proxy={{ no_proxy }} ./reporting_send.py -d {{ansible_env.HOME}}/InsightAgent-master/syscall -D {{ansible_env.HOME}}/InsightAgent-master &)"
  become: true
  async: 10
  poll: 0
  become_flags: '-E'
  args:
    chdir: "{{ansible_env.HOME}}/InsightAgent-master/syscall"
  when: projectDir == "" and default_dir.stat.exists
