---
- name : Check Mandatory Variables For Install
  debug:
    msg:
      - tracingInterval:{{ tracingInterval | mandatory }}
- name: Check for existing project
  stat:
    path: "{{ projectDir }}"
  register: project_dir
  when: projectDir != ""
- name: Check for existing project
  stat:
    path: "{{ansible_env.HOME}}/InsightAgent-master"
  register: default_dir
  when: projectDir == ""
- name: Check for existing pyenv
  stat:
    path: "{{ansible_env.HOME}}/InsightAgent-master/pyenv"
  register: pyenv_default
  when: projectDir == "" and default_dir.stat.exists
- name: Check for existing pyenv
  stat:
    path: "{{ projectDir }}/pyenv"
  register: pyenv_custom
  when: projectDir != "" and project_dir.stat.exists
- name: Activate pyenv - Default dir
  shell: 'bash -lc "source {{ansible_env.HOME}}/InsightAgent-master/pyenv/bin/activate"'
  when: pyenv_default.stat.exists
- name: Activate pyenv - Custom dir
  shell: 'bash -lc "source {{ projectDir }}/pyenv/bin/activate"'
  when: pyenv_custom|failed and pyenv_custom.stat.exists
- name: Install Syscall Agent
  shell: "http_proxy={{ http_proxy }} syscall/installLttng.py -d {{ansible_env.HOME}}/InsightAgent-master/"
  become: true
  args:
    chdir: "{{ansible_env.HOME}}/InsightAgent-master/"
  when: projectDir == "" and default_dir.stat.exists
- name: Install Syscall Agent
  shell: "http_proxy={{ http_proxy }} syscall/installLttng.py -d {{projectDir}}"
  become: true
  args:
    chdir: "{{ projectDir }}"
  when: projectDir != ""  and project_dir.stat.exists
- name: Deploy Syscall Agent
  command: ./getSysTrace.sh -t {{tracingInterval}}
  become: true
  become_flags: '-E'
  args:
    chdir: "{{ projectDir }}/syscall"
  when: projectDir != "" and project_dir.stat.exists
- name: Deploy Syscall Agent
  command: ./getSysTrace.sh -t {{tracingInterval}}
  become: true
  become_flags: '-E'
  args:
    chdir: "{{ansible_env.HOME}}/InsightAgent-master/syscall"
  when: projectDir == "" and default_dir.stat.exists
- name: check processes syscall
  become: yes
  shell: ps -ef | grep reporting_send.py | awk '{printf "%s ",$2}'
  register: awk_test
- name: Stop syscall process
  become: yes
  shell: "kill -9 {{item}}"
  ignore_errors: yes
  with_items:
    - "{{ awk_test.stdout_lines }}"
- name: Start Syscall Agent Listener
  shell: "unset http_proxy https_proxy && ./reporting_send.py -d {{projectDir}}/syscall -D {{projectDir}} -w {{ifReportingUrl}} &"
  become: true
  async: 10
  poll: 0
  become_flags: '-E'
  args:
    chdir: "{{ projectDir }}/syscall"
  when: projectDir != ""  and project_dir.stat.exists
- name: Start Syscall Agent Listener
  shell: "unset http_proxy https_proxy && ./reporting_send.py -d {{ansible_env.HOME}}/InsightAgent-master/syscall -D {{ansible_env.HOME}}/InsightAgent-master -w {{ifReportingUrl}} &"
  become: true
  async: 10
  poll: 0
  become_flags: '-E'
  args:
    chdir: "{{ansible_env.HOME}}/InsightAgent-master/syscall"
  when: projectDir == "" and default_dir.stat.exists