---
- name : Check Mandatory Variables For Install
  debug:
    msg: 
      - ProjectName:{{ projectName | mandatory }} 
      - UserName:{{ userName | mandatory }}
      - Sampling Interval:{{ samplingInterval | mandatory }}
      - Agent Type:{{ agentType | mandatory }}
      - License Key:{{ licenseKey | mandatory }}
- name: Install package dependencies - YUM
  become: yes
  package: 
    name: "{{item}}" 
    state: latest
  with_items:
    - gcc
    - wget
    - libffi-devel
    - python-devel
    - openssl-devel
  when: ansible_pkg_mgr == 'yum'
- name: Install package dependencies - APT
  become: yes
  apt: 
    name: "{{item}}" 
    state: latest
    #update_cache: yes
  with_items:
    - build-essential
    - libssl-dev
    - libffi-dev
    - python-dev
    - wget
  when: ansible_pkg_mgr == 'apt'
- name: Delete Old Tar Bundle for Agent
  become: yes
  file:
    state: absent
    path: "{{ansible_env.HOME}}/insightagent.tar.gz"
- name: Delete Old Agent Code
  become: yes
  file:
    state: absent
    path: "{{ansible_env.HOME}}/InsightAgent-master"
- name: Copy Agent Code on Machines
  become: yes
  copy:
    src: ../files/insightagent.tar.gz
    dest: "{{ansible_env.HOME}}"
    owner: root
    group: root
    mode: 0644
- name: Untar the Agent Code
  unarchive: 
    src: "{{ansible_env.HOME}}/insightagent.tar.gz"
    dest: "{{ansible_env.HOME}}"
    remote_src: True
- name: Create Python Virtual Environment for Agent
  command: ./deployment/checkpackages.sh -env
  args:
    chdir: "{{ansible_env.HOME}}/InsightAgent-master"
- name: Deploy cgroup Agent
  command: >
    ./deployment/install.sh 
    -i {{ projectName }} 
    -u {{ userName }} 
    -k {{ licenseKey }} 
    -s {{ samplingInterval }} 
    -t {{ agentType }}
    -w {{ reportingUrl }}
  become: true
  args:  
    chdir: "{{ansible_env.HOME}}/InsightAgent-master/"
- name: Delete Tar Bundle for Agent
  file:
    state: absent
    path: "{{ansible_env.HOME}}/insightagent.tar.gz"
