#=========================== Filebeat inputs =============================
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - <Path to log file>
  exclude_lines: ['^#']
  fields:
    log_type: <Tag for logstash processing (eg: appserver)> 
    

#================================ Outputs ======================================
output.logstash:
  enabled: true
  hosts: ["<Logstash server with port>"]
